AWSTemplateFormatVersion: 2010-09-09

Description: |
  I created this cfn in my free time.
  
Parameters:
  ParameterKeypair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select your keypair to connect with SSH.

  ParameterSG:
    Description: 22 port
    Type: AWS::EC2::SecurityGroup::GroupName
    

Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ebfd941bbafe70c6
      InstanceType: t2.micro
      KeyName: !Ref ParameterKeypair
      SecurityGroups: 
        - !Ref ParameterSG
      Tags: 
        - Key: Name
          Value: cfn-1
      UserData: 
        !Base64 |
        #! /bin/bash
        yum update -y 
        yum install python3
        pip3 install flask
  
      
  
